apiVersion: apps/v1
kind: Deployment
metadata:
  name: trabzonspor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trabzonspor
  template:
    metadata:
      labels:
        app: trabzonspor
    spec:
      containers:
        - name: trabzonspor
          image: nginx:latest
          imagePullPolicy: "Always"
          env:
          - name: FOR_ROLLOUT
            value: 'AAAAA'
          ports:
          - name: http
            containerPort: 8080
          volumeMounts:
          - name: tz
            mountPath: /etc/localtime
      volumes:
      - name: tz
        hostPath:
          path: /usr/share/zoneinfo/Europe/Istanbul